### PR TITLE
Fix insert method call and log fails on send

### PR DESCRIPTION
**Pull request by Eseperio**

### CODE REVIEW

**Comment by tuyakhov** [comment]
Logging in extension is not a good idea since the developer won't have full control over the format of the log messages. We should also remove the other `\Yii::info()` from there.
It's better to use an even listener for `EVENT_AFTER_SEND` and do all the logging and/or other operations on the result there.

**Comment by tuyakhov** [comment]
You can change your app config to something like this:
```
[
   'components' => [
       'notifier' => [
           'class' => '\tuyakhov\notifications\Notifier',
           'channels' => [ ... ],
           'on afterSend' => function (NotificationEvent $event) {
              Yii::info("Notification sent via " . $event->channel);
           }
       ],
   ],
]
```
`$event` property has all the necessary details about notification, recipient as well as the output of `send` method.

**Comment by Eseperio** [comment]
Yii core is full of logs that help improve the work. Why an extension should´nt have them? 
If a developer want to log more information it can use the event, but at least must have some information. 
What can not be done in developing is hiding an exception.  I spent about an hour inspecting the code trying to figure out why my mail notification wasn´t been sent. If i would had that Yii::error line it had cost me about 1 second.

**Comment by Eseperio** [comment]
@tuyakhov Check the last change https://github.com/tuyakhov/yii2-notifications/pull/10/commits/7fada54cfaf6a089eb091dd45251c9eeef5b0b04 
It fixes a problem when you try to send two different notifications within the same channel.

The problem is that Yii2 insert method only inserts those attributes that are dirty, and if we reuse model instance, nothing is saved except those parameters we have updated.

**Pull request closed without merging**
